import 'package:sneakerapp/model/shoemodel.dart';

final List<Shoe> dummyShoes = [
  Shoe(
    id: '1',
    name: 'Nike Air Max',
    brand: 'Nike',
    price: 120.0,
    reviews: [
      Review(userId: 'zeb', comment: 'Great shoe!', rating: 5.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 4.5),
      Review(userId: 'shady', comment: 'best shoe!', rating: 3.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 2.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 1.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 3.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 4.0),
      Review(userId: 'shady', comment: 'Comfortable fit.', rating: 3.5),
    ],
    averageRating: 5.0,
    imageUrl: 'assets/shoe1.png',
  ),
  Shoe(
    id: '1',
    name: 'Nike Air Max',
    brand: 'Nike',
    price: 120.0,
    reviews: [
      Review(userId: 'zeb', comment: 'Great shoe!', rating: 5.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 4.5),
      Review(userId: 'shady', comment: 'best shoe!', rating: 3.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 2.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 1.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 3.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 4.0),
      Review(userId: 'shady', comment: 'Comfortable fit.', rating: 3.5),
    ],
    // numberOfReviews: 25,
    averageRating: 5.0,
    imageUrl: 'assets/shoe1.png',
  ),
  Shoe(
    id: '2',
    name: 'Adidas Ultraboost',
    brand: 'Adidas',
    price: 150.0,
    reviews: [
      Review(userId: 'zeb', comment: 'Great shoe!', rating: 5.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 4.5),
      Review(userId: 'shady', comment: 'best shoe!', rating: 3.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 2.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 1.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 3.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 4.0),
      Review(userId: 'shady', comment: 'Comfortable fit.', rating: 3.5),
    ],
    // numberOfReviews: 18,
    averageRating: 4.2,
    imageUrl: 'assets/shoe2.png',
  ),
  Shoe(
    id: '3',
    name: 'Nike Air Max', brand: 'Nike',
    price: 120.0,
    reviews: [
      Review(userId: 'zeb', comment: 'Great shoe!', rating: 5.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 4.5),
      Review(userId: 'shady', comment: 'best shoe!', rating: 3.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 2.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 1.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 3.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 4.0),
      Review(userId: 'shady', comment: 'Comfortable fit.', rating: 3.5),
    ],
    // numberOfReviews: 25,
    averageRating: 3.8,
    imageUrl: 'assets/shoe3.png',
  ),
  Shoe(
    id: '4',
    name: 'Adidas Ultraboost', brand: 'Adidas',
    price: 150.0,
    reviews: [
      Review(userId: 'zeb', comment: 'Great shoe!', rating: 5.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 4.5),
      Review(userId: 'shady', comment: 'best shoe!', rating: 3.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 2.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 1.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 3.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 4.0),
      Review(userId: 'shady', comment: 'Comfortable fit.', rating: 3.5),
    ],
    // numberOfReviews: 18,
    averageRating: 4.2,
    imageUrl: 'assets/shoe4.png',
  ),
  Shoe(
    id: '5',
    name: 'Nike Air Max',
    brand: 'Nike',
    price: 120.0,
    reviews: [
      Review(userId: 'zeb', comment: 'Great shoe!', rating: 5.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 4.5),
      Review(userId: 'shady', comment: 'best shoe!', rating: 3.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 2.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 1.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 3.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 4.0),
      Review(userId: 'shady', comment: 'Comfortable fit.', rating: 3.5),
    ],
    // numberOfReviews: 25,
    averageRating: 4.8,
    imageUrl: 'assets/shoe3.png',
  ),
  Shoe(
    id: '6',
    name: 'Adidas Ultraboost',
    brand: 'Adidas',
    price: 150.0,
    reviews: [
      Review(userId: 'zeb', comment: 'Great shoe!', rating: 5.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 4.5),
      Review(userId: 'shady', comment: 'best shoe!', rating: 3.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 2.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 1.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 3.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 4.0),
      Review(userId: 'shady', comment: 'Comfortable fit.', rating: 3.5),
    ],
    // numberOfReviews: 18,
    averageRating: 3.0,
    imageUrl: 'assets/shoe4.png',
  ),
  Shoe(
    id: '7',
    name: 'Nike Air Max', brand: 'Nike',
    price: 120.0,
    reviews: [
      Review(userId: 'zeb', comment: 'Great shoe!', rating: 5.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 4.5),
      Review(userId: 'shady', comment: 'best shoe!', rating: 3.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 2.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 1.0),
      Review(userId: 'rax', comment: 'Comfortable fit.', rating: 3.5),
      Review(userId: 'shady', comment: 'Great shoe!', rating: 4.0),
      Review(userId: 'shady', comment: 'Comfortable fit.', rating: 3.5),
    ],
    // numberOfReviews: 25,
    averageRating: 4.0,
    imageUrl: 'assets/shoe1.png',
  ),
];
